openapi: 3.1.0
info:
  title: Restaurant API
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Local development servers
  - url: https://restaurant-api-nj73.onrender.com
    description: Production server on render
tags:
  - name: Users
    description: User-related endpoints
  - name: Menu
  - name: Restaurants
    description: Restaurant-related endpoints
paths:
  /api/users:
    get:
      summary: List all users
      tags:
        - Users
      parameters:
        - name: limit
          in: query
          description: Maximum number of users to return
          required: false
          schema:
            type: integer
            default: 10
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
    post:
      summary: Create a new user
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                error: Validation failed
                details: Name is required
  /api/users/me:
    get:
      summary: Get current user
      tags:
        - Users
      responses:
        '200':
          description: Successful response with current user details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                error: Unauthorized
                details: Authentication credentials were missing or incorrect
    put:
      summary: Update current user
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: User updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                error: Validation failed
                details: An email, password, or phone number must be provided to update
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                error: Unauthorized
                details: Authentication credentials were missing or incorrect
    delete:
      summary: Delete current user
      tags:
        - Users
      responses:
        '204':
          description: User deleted successfully
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                error: Unauthorized
                details: Authentication credentials were missing or incorrect
  /api/menu:
    get:
      summary: List all menu items
      tags:
        - Menu
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/menuItem'
        '400':
          $ref: '#/components/responses/BadRequest'
    post:
      summary: Create a menu item
      tags:
        - Menu
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/menuItem'
      responses:
        '201':
          description: Menu item created
        '400':
          $ref: '#/components/responses/BadRequest'
  /api/menu/{id}:
    get:
      summary: Get menu item by ID
      tags:
        - Menu
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of menu item to get
          schema:
            type: integer
            example: 1
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/menuItem'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
    put:
      summary: Update a menu item
      tags:
        - Menu
      parameters:
        - name: id
          in: path
          description: ID of menu item
          required: true
          schema:
            type: integer
            example: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/menuItem'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/menuItem'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
    delete:
      summary: Delete a menu item
      tags:
        - Menu
      parameters:
        - name: id
          in: path
          description: ID of the menu item to delete
          required: true
          schema:
            type: integer
      responeses:
        '204':
          description: Menu item deleted
        '400':
          $ref: ../components/responses/BadRequest.yaml
        '404':
          $ref: ../components/responses/NotFound.yaml
  /api/restaurants:
    get:
      summary: List all restaurants
      tags:
        - Restaurant
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Restaurant'
        '400':
          $ref: '#/components/responses/BadRequest'
    post:
      summary: Create a restaurant
      tags:
        - Restaurant
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Restaurant'
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Restaurant'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                error: Validation failed
                details: Name is required
  /api/restaurants/{id}:
    get:
      summary: Get restaurant by ID
      tags:
        - Restaurant
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of retaurant to get
          schema:
            type: integer
            example: 1
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Restaurant'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                error: Validation failed
                details: ID must be a positive integer
        '404':
          description: No results found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                error: Not found
                details: No restaurant exists with the given ID
    put:
      summary: Update a restaurant
      tags:
        - Restaurant
      parameters:
        - name: id
          in: path
          description: ID of restaurant
          required: true
          schema:
            type: integer
            example: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Restaurant'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Restaurant'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                error: Validation failed
                details: Name is required
        '404':
          description: No results found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                error: Not found
                details: No restaurant exists with the given ID
    delete:
      summary: Delete restaurant by ID
      tags:
        - Restaurant
      parameters:
        - name: id
          in: path
          description: ID of the restaurant to delete
          required: true
          schema:
            type: integer
            example: 1
      responses:
        '204':
          description: Restaurant deleted successfully
        '404':
          description: No results found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                error: Not found
                details: No restaurant exists with the given ID
  /api/reservation:
    get:
      summary: List all reservations
      tags:
        - Reservations
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/reservation'
        '400':
          $ref: '#/components/responses/BadRequest'
    post:
      summary: Create a Reservation
      tags:
        - Reservations
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/reservation'
      responses:
        '201':
          description: reservation item created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/reservation'
        '400':
          $ref: '#/components/responses/BadRequest'
  /api/reservation/{id}:
    get:
      summary: Get reservation item by ID
      tags:
        - Reservations
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of reservation to get
          schema:
            type: integer
            example: 1
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/reservation'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
    patch:
      summary: Update a reservation status to canceled
      tags:
        - Reservations
      parameters:
        - name: id
          in: path
          description: ID of reservation
          required: true
          schema:
            type: integer
            example: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/reservation'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/reservation'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
    delete:
      summary: Delete a reservation
      tags:
        - Reservations
      parameters:
        - name: id
          in: path
          description: ID of the reservation to delete
          required: true
          schema:
            type: integer
      responeses:
        '204':
          description: Reservation deleted
        '400':
          $ref: ../components/responses/BadRequest.yaml
        '404':
          $ref: ../components/responses/NotFound.yaml
components:
  schemas:
    User:
      type: object
      properties:
        id:
          readOnly: true
          type: integer
          example: 1
        name:
          type: string
          example: Alice Green
        email:
          type: string
          example: alice@demo.com
        phone:
          type: string
          example: 123-456-7890
    Error:
      type: object
      properties:
        error:
          type: string
        details:
          type: string
    menuItem:
      type: object
      properties:
        id:
          readOnly: true
          type: integer
          example: 1
        name:
          type: string
          example: Pizza
        price:
          type: number
          example: 5.99
        restaurantId:
          type: integer
          example: 1
    ValidationError:
      type: object
      properties:
        error:
          type: string
          example: Validation failed
        details:
          type: array
          items:
            type: string
    NotFoundError:
      type: object
      properties:
        error:
          type: string
          example: Task not found
    Restaurant:
      type: object
      properties:
        id:
          readOnly: true
          type: integer
          example: 1
        name:
          type: string
          example: Italian Restaurant
        address:
          type: string
          example: 123 Main St
        phone:
          type: string
          example: 555-123
        openingTime:
          type: string
          format: time
          example: '2025-01-01T12:00:00Z'
        closingTime:
          type: string
          format: time
          example: '2025-01-01T22:00:00Z'
        menuItems:
          type: array
          items:
            $ref: '#/components/schemas/menuItem'
    reservation:
      type: object
      properties:
        id:
          readOnly: true
          type: integer
          example: 1
        userId:
          type: integer
          example: 2
        restaurantId:
          type: integer
          example: 1
        reservationTime:
          type: string
          format: date-time
          example: 2025-11-0217:22:00
        partySize:
          type: integer
          example: 5
        status:
          type: string
          enum:
            - CONFIRMED
            - CANCELED
          example: CONFIRMED
        createdAt:
          type: string
          format: date-time
          example: 2025-11-0212:30:00
  responses:
    BadRequest:
      description: Invalid input
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ValidationError'
    NotFound:
      description: Not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/NotFoundError'
